### ISSUE TITLE
React 18

### ISSUE THREAD

**Issue by cubucul** [ibitcy/eo-locale#100]
Hi! I like to use your library, but it does not work with React 18.

```
npx create-react-app my-app
cd my-app
npm i @eo-locale/react --save
```

**Comment by ruslanchek** [comment]
Hi! Thank you! I’ve planned to upgrade it to React 18 today

**Comment by pret-a-porter** [comment]
Beta version released https://www.npmjs.com/package/@eo-locale/core/v/1.6.0-beta.0

**Comment by cubucul** [comment]
I have an error when I am trying to install beta with npm
```
npm i @eo-locale/react@1.6.0-beta.0
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:^
```

**Comment by pret-a-porter** [comment]
@cubucul thank you for reporting! Try 1.6.0-beta.1 please

**Comment by cubucul** [comment]
@pret-a-porter beta 1 installed without error, but app compile with problem:
```
ERROR in ./node_modules/@eo-locale/react/lib/index.js 3:0-64

Module not found: Error: Package path ./server.js is not exported from package /my-app/node_modules/react-dom (see exports field in /my-app/node_modules/react-dom/package.json)
```
