### ISSUE TITLE
IDE auto-import behaviour incorrect

### ISSUE THREAD

**Issue by ruslanchek** [ibitcy/eo-locale#12]
IDE auto-import behavior is incorrect.
In .tsx file If you start to type `<EOLocale...` IntelliSense or JetBrains autocomplete offers you to auto-import such things:

`EOLocaleDate,
EOLocaleText, ...`

That is correct (as a regular coder thinks), but for example, EOLocaleText won't work after all, at compile time it throws this error:

`Module not found: Can't resolve 'eo-locale/dist/components/text' in '~/.../component'`

And after small research, you see that correct way is to use it like this: 

`import { EOLocale } from 'eo-locale';
...
<EOLocale.Text />
`

Can we just use both ways? Or, to be more strict only one of the ways.

**Comment by pret-a-porter** [comment]
Solved in `@eo-locale/react`. Try to use it)
