### ISSUE TITLE
How to provide <EOLocale.Text /> component to <input /> placeholder

### ISSUE THREAD

**Issue by kilgarenone** [ibitcy/eo-locale#14]
Does anyone know how to render the string in my `<EOLocale.Text id="placeholder" />` in a `<input />`'s placeholder?

```
<input placeholder={<EOLocale.Text id="placeholder" />}
```
I'm getting `[object object]` when I do that...

**Comment by ruslanchek** [comment]
You can use the translator hook. Just like that:
`const translator = useTranslator();
...
<input placelohder={translator.translate('PHRASE')} />
`

**Comment by kilgarenone** [comment]
Any way without using hooks?

**Comment by ruslanchek** [comment]
Yes, using Context or Translator instance.
Look at the example: https://codesandbox.io/s/weathered-wildflower-c7l3j

**Comment by kilgarenone** [comment]
Thank you very much for that! 👍
