### ISSUE TITLE
memoize result of delve function

### ISSUE THREAD

**Issue by stalniy** [ibitcy/eo-locale#19]
It's a good practice to memoize results of a function that returns value from nested object by dot notation. This speeds things up, especially for React.

**Update**: this bug report relates to `Translator.translate` method from `@eo-locale/core` but I can't find bug tracker for it

**Comment by pret-a-porter** [comment]
@stalniy nice idea

`delve` function is used [here](https://github.com/eo-locale/core/blob/master/src/translator.ts)

I will appreciate for merge request

**Comment by pret-a-porter** [comment]
Solved https://github.com/ibitcy/eo-locale/commit/4b5d9e159d49004174a20cbcecde41ac3dd0892d
