### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by 404-html** [ibitcy/eo-locale#20]
It would be nice for library to work with React Native.
I had troubles installing it. It was asking for `react-dom` which isn't a best fit for RN apps.
Finally using components inside RN app was throwing exceptions so I assume it's not RN friendly.

**Comment by pret-a-porter** [comment]
@404-html `react-dom` is used for availability pass `React.Component` as prop. I will research solution of this problem.

**Comment by pret-a-porter** [comment]
`@eo-locale/react-native` was published. Try to use it. It works fine in hello world project, but I have not a lot of experience in React Native.

**Comment by 404-html** [comment]
Amazing! Thank you @pret-a-porter, I'll give it a go soon and come back to you.

**Comment by 404-html** [comment]
Unfortunately I have troubles making it working in React Native project. I'm getting following error:

![image](https://user-images.githubusercontent.com/45104241/86522491-e7009600-be5e-11ea-8db1-5478c3850520.png)

Here's what I'm trying to do:

```js
import { EOLocale } from '@eo-locale/react-native';
...
<EOLocale.Number value={1000} />
```

**Comment by pret-a-porter** [comment]
Sorry, I did not update documentation. `@eo-locale/react-native` exports these components: `Numeric, Translation, DateTime, TranslationsProvider`.

**Comment by pret-a-porter** [comment]
Finally I have added react-native documentation https://eo-locale.netlify.app/docs/react-native/install
