### ISSUE TITLE
Date doc — value of the select widget overflows container

### ISSUE THREAD

**Issue by ilyalesik** [ibitcy/eo-locale#25]
[Date](https://eo-locale.netlify.app/docs/Date)

<img width="791" alt="Screenshot 2020-07-19 at 14 00 08" src="https://user-images.githubusercontent.com/1270648/87873221-672f0b80-c9c8-11ea-96dc-101d69fc3b03.png">

**Comment by pret-a-porter** [comment]
@ilyalesik Fixed! Thanks a lot
