### ISSUE TITLE
Move preact version in main repo

### ISSUE THREAD

**Issue by pret-a-porter** [ibitcy/eo-locale#30]
Move https://github.com/eo-locale/preact in packages directory

**Comment by eavam** [comment]
Can I do it?

**Comment by pret-a-porter** [comment]
@eavam yes, sure

**Comment by eavam** [comment]
Ready #33 😁

**Comment by eavam** [comment]
And I think you need to add the "hacktoberfest" topic to the repository 🙂

**Comment by eavam** [comment]
> And I think you need to add the "hacktoberfest" topic to the repository 🙂

Otherwise, this repository is not tracked for Hacktoberfest.

**Comment by pret-a-porter** [comment]
@eavam could you make it too?) Can I merge your request? Is it counted in your hacktoberfest profile?))

**Comment by eavam** [comment]
> Is it counted in your hacktoberfest profile?

Unfortunately not. Please try to add a tag to the repository topic.
<img width="364" alt="Screenshot 2020-10-06 at 20 56 48" src="https://user-images.githubusercontent.com/16797465/95211407-be4dbb00-0816-11eb-8dce-6706f58d34bc.png">

**Comment by pret-a-porter** [comment]
Done

**Comment by eavam** [comment]
Thank you so much. Merge PR, please. 😁
