### ISSUE TITLE
Validate and improve documentation

### ISSUE THREAD

**Issue by pret-a-porter** [ibitcy/eo-locale#31]

**Comment by icegotcha** [comment]
I will do it. Please assign to me.

**Comment by pret-a-porter** [comment]
@icegotcha done

**Comment by icegotcha** [comment]
Hello @pret-a-porter,
Currently, I'm improving the document about components and core functions.
I will finish resolving this issue this weekend.

**Comment by pret-a-porter** [comment]
Hello @icegotcha,
Cool, thank you! Take your time

**Comment by icegotcha** [comment]
Hello @pret-a-porter,
I'm going to create a PR. Which branch should I merge? develop or master?

**Comment by pret-a-porter** [comment]
@icegotcha master

**Comment by icegotcha** [comment]
@pret-a-porter 
Done #34

**Comment by pret-a-porter** [comment]
@icegotcha Merged! Thanks a lot!
