### ISSUE TITLE
Can not format date, number, and plural in React Native

### ISSUE THREAD

**Issue by icegotcha** [ibitcy/eo-locale#35]
I found a problem when use components & useTranslator to format date, number, and plural.
They throw an error 'Can't find variable: Intl' like this:

![image](https://user-images.githubusercontent.com/32319739/95773502-cdd27580-0ce8-11eb-95cc-c67080f9b065.png)

**Comment by icegotcha** [comment]
Finally, I found a solution.
This because React Native runs JavaScript Core (JSC) that does not support Intl by default.
I must change the JSC and rebuild my project, and `eo-locale` can run normally.
In React Native 0.60 or newer, I can change it by just update one line in file `android/app/build.gradle`.
```
/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than the default.
 */
 - def jscFlavor = 'org.webkit:android-jsc:+'
 + def jscFlavor = 'org.webkit:android-jsc-intl:+'
```
(from: https://github.com/moment/luxon/issues/604)

In React Native 0.59, I need to install an NPM dependency: `jsc-android`

```
dependencies {
+  "jsc-android": "241213.1.1",
```

install an android dependency in file `android/app/build.gradle`
```
dependencies {
    implementation "org.webkit:android-jsc-intl:r241213"
    implementation fileTree(dir: "libs", include: ["*.jar"])
    ...
}
```
(add at first of dependencies section)


Add packagingOptions in android section in the same file

```
android {
    // ...
+   packagingOptions {
+       pickFirst '**/libjsc.so'
+       pickFirst '**/libc++_shared.so'
+    }
}
```
And change jsc to `org.webkit:android-jsc-intl:+`

I will add this information to your documentation (installation section)

**Comment by pret-a-porter** [comment]
@icegotcha Awesome!

**Comment by ayubov** [comment]
@icegotcha thank you for this comment, it worked for me too!
