### ISSUE TITLE
Differences in Preact API

### ISSUE THREAD

**Issue by piotr-cz** [ibitcy/eo-locale#36]
The `@eo-locale/preact` API is different than `@eo-locale/react` in:

- Components are exported in `EOLocale` namespace
   ```js
   import { EOLocale } from '@eo-locale/preact'

   const TranslationsProvider = EOLocale.Provider
   const Text = EOLocale.Text
   ```

- TranslationsProvider doesn't use the `setLanguage` function

- The [`useTranslator`](https://eo-locale.netlify.app/docs/apis/useTranslator) hook is not implemented

Reference: #30

**Comment by pret-a-porter** [comment]
@piotr-cz Thanks! Can you fix it?

**Comment by piotr-cz** [comment]
I've tried, but failed badly because of problems related to TypeScript and Lerna.
I may try again but for now I've decided to use other package.

**Comment by pret-a-porter** [comment]
@piotr-cz Got it, thanks for issue!

**Comment by pret-a-porter** [comment]
@piotr-cz it should work in version 1.4.5

**Comment by piotr-cz** [comment]
Thank you, I'll check it out

**Comment by piotr-cz** [comment]
Works great, thank you! ❤️
