### ISSUE TITLE
Cannot read property 'getMessageById' of undefined

### ISSUE THREAD

**Issue by puema** [ibitcy/eo-locale#42]
Hey, a nice package you have there 👍 

### Current behavior
When using `useTranslator()` in @eo-locale/preact I'm unfortunately getting a
`Uncaught (in promise) TypeError: Cannot read property 'getMessageById' of undefined`.

### To reproduce
[Codesandbox](https://codesandbox.io/s/eo-locale-issue-8jhy2)

### Expected
Message is correctly translated

### Environment
* `parcel` 1.12.4
* `preact` 10.5.7
* `@eo-locale/preact` 1.4.10

**Comment by pret-a-porter** [comment]
@puema Hi, thank for your issue. I am ready to help you, but I need more information.

**Comment by puema** [comment]
Hi @pret-a-porter,
Thanks for the fast reply and for looking into this. Sure, I just didn't have time to create a repo yesterday.
The setup is typescript, preact (with aliasing to compat), and parcel.
[Here](https://codesandbox.io/s/eo-locale-issue-8jhy2) is a sandbox with the isolated issue.

**Comment by pret-a-porter** [comment]
@puema Thanks! Context of function was lost. I will fix it. As fast fix just change to `const translator = useTranslator();` and use `translator.translate(...)`.

**Comment by pret-a-porter** [comment]
@puema fixed in 1.4.11
