### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by westmark** [ibitcy/eo-locale#47]
Hi! For all versions above 1.4.7, I'm getting the error below:

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /xxxxxxxx/node_modules/@eo-locale/core/lib/index.js
require() of ES modules is not supported.
require() of /xxxxxxxx/node_modules/@eo-locale/core/lib/index.js from /xxxxxxx/node_modules/@eo-locale/react/lib/index..
Instead rename /xxxxxxx/node_modules/@eo-locale/core/lib/index.js to end in .cjs, change the requiring code to use import(), or remove "type: module"
```

In 1.4.8 the new `exports` and `type` properties were introduced in `package.json` for both `@eo-locale/core` and `@eo-locale/react` (possibly other packages as well - I didn't check). 

I'm not familiar with these properties but apparently, for node > 13 they will cause an exception when misconfigured, whereas in node < 13 they will merely emit a warning.

Downgrading to `@eo-locale/react@1.4.7` solved the issue. I also had to add a resolution for the same version for `@eo-locale/core` since 1.4.11 will be auto-installed otherwise. The error above is emitted for both packages.

**Comment by pret-a-porter** [comment]
@westmark Hi! Thank you for your issue! Please, could you provide more context? Code example of usage. Which version of nodejs do you use?

**Comment by pret-a-porter** [comment]
All versions above 1.4.7 uses next [approach](https://nodejs.org/api/packages.html#packages_approach_1_use_an_es_module_wrapper)

**Comment by westmark** [comment]
I'm using Node `v15.3.0`. I am not at liberty to share any of the code I'm working on, but since this is an import issue I don't see how it could make any difference. In any case, according to the docs you are referring to

>The preceding example uses explicit extensions .mjs and .cjs. If your files use the .js extension, "type": "module" will cause such files to be treated as ES modules

...you should not use the .js extension for your output files, since all .js files will be treated as ES modules when `type` = `module`, which is probably not what you want.

**Comment by pret-a-porter** [comment]
@westmark I have reproduced the problem. I will try to fix it.

**Comment by pret-a-porter** [comment]
@westmark Please, check version 1.4.13

**Comment by westmark** [comment]
Hi, sorry for the delay. This works fine now 👍
