### ISSUE TITLE
React v17

### ISSUE THREAD

**Issue by SanichKotikov** [ibitcy/eo-locale#56]
Hi!

First of all, thanks for your lib.

```
npm i @eo-locale/react --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: react-eo-locale@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from @eo-locale/react@1.4.14
npm ERR! node_modules/@eo-locale/react
npm ERR!   @eo-locale/react@"*" from the root project
```

I suppose it should be something like `"react": ">= 16.8.0"`

**Comment by pret-a-porter** [comment]
@SanichKotikov Thank you for the issue! I will try to investigate soon

**Comment by pret-a-porter** [comment]
@SanichKotikov Unfortunately I could not  reproduce the issue. Could you please provide steps for reproduce the problem. I have tried reproduce by next way:
````ts
npx create-react-app my-app
cd my-app
npm @eo-locale/react --save
````

**Comment by SanichKotikov** [comment]
@pret-a-porter same steps. Maybe it's `npm` version issue, I use `7.6.3`.

**Comment by sayutinav** [comment]
Hi! Try this:
`npm i @eo-locale/react --save --legacy-peer-deps`

**Comment by pret-a-porter** [comment]
I have fixed peer deps, will publish new version a bit later
